
const moviesActionTypes = {
    FETCH_SEARCHED_MOVIES: 'FETCH_SEARCHED_MOVIES',
    FETCH_TRENDING_MOVIES: 'FETCH_TRENDING_MOVIES',
    FETCH_POPULAR_MOVIES: 'FETCH_POPULAR_MOVIES',
    CHANGE_FETCH_STATUS: 'CHANGE_FETCH_STATUS',
    CHANGE_CURRENTLY_VIEWED_MOVIE: 'CHANGE_CURRENTLY_VIEWED_MOVIE'
}

export default moviesActionTypes;