const userActionTypes = {
    LOAD_USER_DATA: 'LOAD_USER_DATA',
    LOG_OUT_USER: 'LOG_OUT_USER',
    SET_FAVOURITE_MOVIE: 'SET_FAVOURITE_MOVIE',
    REMOVE_FAVOURITE_MOVIE: 'REMOVE_FAVOURITE_MOVIE',
    SET_MUST_WATCH_MOVIE: 'SET_MUST_WATCH_MOVIE',
    REMOVE_MUST_WATCH_MOVIE: 'REMOVE_MUST_WATCH_MOVIE',
}

export default userActionTypes