const userActionTypes = {
    LOAD_USER_DATA: 'LOAD_USER_DATA',
    LOG_OUT_USER: 'LOG_OUT_USER',
    SET_FAVOURITE_MOVIE: 'SET_FAVOURITE_MOVIE',
    REMOVE_FAVOURITE_MOVIE: 'REMOVE_FAVOURITE_MOVIE',
    SET_MUST_WATCH_MOVIE: 'SET_MUST_WATCH_MOVIE',
    REMOVE_MUST_WATCH_MOVIE: 'REMOVE_MUST_WATCH_MOVIE',
    REQUEST_USER_DATA_PENDING: 'REQUEST_USER_DATA_PENDING',
    REQUEST_USER_DATA_SUCCESS: 'REQUEST_USER_DATA_SUCCESS',
    REQUEST_USER_DATA_FAILED: 'REQUEST_USER_DATA_FAILED',
    REGISTER_NEW_USER_PENDING: 'REGISTER_NEW_USER_PENDING',
    REGISTER_NEW_USER_SUCCESS: 'REGISTER_NEW_USER_SUCCESS',
    REGISTER_NEW_USER_FAILED: 'REGISTER_NEW_USER_FAILED',
}

export default userActionTypes