
const moviesActionTypes = {
    FETCH_SEARCHED_MOVIES: 'FETCH_SEARCHED_MOVIES',
    FETCH_TRENDING_MOVIES: 'FETCH_TRENDING_MOVIES',
    FETCH_POPULAR_MOVIES: 'FETCH_POPULAR_MOVIES',
    CHANGE_IS_FETCHING: 'CHANGE_IS_FETCHING',
    CHANGE_CURRENTLY_VIEWED_MOVIE: 'CHANGE_CURRENTLY_VIEWED_MOVIE',
    SET_SIMILAR_MOVIES_DATA: 'SET_SIMILAR_MOVIES_DATA',
    SET_MOVIE_CAST_DATA: 'SET_MOVIE_CAST_DATA',
    REQUEST_MOVIE_SECTION_DATA_PENDING: 'REQUEST_MOVIE_SECTION_DATA_PENDING',
    REQUEST_MOVIE_SECTION_DATA_SUCCESS: 'REQUEST_MOVIE_SECTION_DATA_SUCCESS',
    REQUEST_MOVIE_SECTION_DATA_FAILED: 'REQUEST_MOVIE_SECTION_DATA_FAILED',
    REQUEST_HOME_PAGE_DATA_PENDING: 'REQUEST_HOME_PAGE_DATA_PENDING',
    REQUEST_HOME_PAGE_DATA_SUCCESS: 'REQUEST_HOME_PAGE_DATA_SUCCESS',
    REQUEST_HOME_PAGE_DATA_FAILED: 'REQUEST_HOME_PAGE_DATA_FAILED',
    REQUEST_SEARCH_DATA_PENDING: 'REQUEST_SEARCH_DATA_PENDING',
    REQUEST_SEARCH_DATA_SUCCESS: 'REQUEST_SEARCH_DATA_SUCCESS',
    REQUEST_SEARCH_DATA_FAILED: 'REQUEST_SEARCH_DATA_FAILED',
    REQUEST_FILTER_DATA_PENDING: 'REQUEST_FILTER_DATA_PENDING',
    REQUEST_FILTER_DATA_SUCCESS: 'REQUEST_FILTER_DATA_SUCCESS',
    REQUEST_FILTER_DATA_FAILED: 'REQUEST_FILTER_DATA_FAILED',
}

export default moviesActionTypes;