
const moviesActionTypes = {
    FETCH_SEARCHED_MOVIES: 'FETCH_SEARCHED_MOVIES',
    FETCH_TRENDING_MOVIES: 'FETCH_TRENDING_MOVIES',
    FETCH_POPULAR_MOVIES: 'FETCH_POPULAR_MOVIES',
    CHANGE_FETCH_STATUS: 'CHANGE_FETCH_STATUS',
    CHANGE_CURRENTLY_VIEWED_MOVIE: 'CHANGE_CURRENTLY_VIEWED_MOVIE',
    ADD_EXTRA_DATA_TO_CURRENTLY_VIEWED_MOVIE: 'ADD_EXTRA_DATA_TO_CURRENTLY_VIEWED_MOVIE',
    SET_SIMILAR_MOVIES_DATA: 'SET_SIMILAR_MOVIES_DATA'
}

export default moviesActionTypes;